# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cowtech-js-rails"
  s.version = "1.0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shogun"]
  s.date = "2012-03-14"
  s.description = "A set of Javascript libraries."
  s.email = "shogun_panda@me.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/cowtech_js.rb",
    "lib/cowtech_js/version.rb",
    "vendor/assets/javascripts/cowtech/accesskeys.coffee",
    "vendor/assets/javascripts/cowtech/autocomplete.coffee",
    "vendor/assets/javascripts/cowtech/bulk.coffee",
    "vendor/assets/javascripts/cowtech/calculator.coffee",
    "vendor/assets/javascripts/cowtech/clipboard.coffee",
    "vendor/assets/javascripts/cowtech/combobox.coffee",
    "vendor/assets/javascripts/cowtech/document.coffee",
    "vendor/assets/javascripts/cowtech/dynamic-table.coffee",
    "vendor/assets/javascripts/cowtech/form.coffee",
    "vendor/assets/javascripts/cowtech/google-analytics.coffee",
    "vendor/assets/javascripts/cowtech/keepalive.coffee",
    "vendor/assets/javascripts/cowtech/messages.coffee",
    "vendor/assets/javascripts/cowtech/modal.coffee",
    "vendor/assets/javascripts/cowtech/numeric.coffee",
    "vendor/assets/javascripts/cowtech/scroll.coffee",
    "vendor/assets/javascripts/cowtech/search.coffee",
    "vendor/assets/javascripts/cowtech/share.coffee",
    "vendor/assets/javascripts/cowtech/utils.coffee",
    "vendor/assets/javascripts/cowtech/wysiwyg.coffee"
  ]
  s.homepage = "http://github.com/ShogunPanda/cowtech-js-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "A set of Javascript libraries."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sprockets>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<rails >= 3.1>, [">= 0"])
    else
      s.add_dependency(%q<sprockets>, [">= 0"])
      s.add_dependency(%q<coffee-script>, [">= 0"])
      s.add_dependency(%q<rails >= 3.1>, [">= 0"])
    end
  else
    s.add_dependency(%q<sprockets>, [">= 0"])
    s.add_dependency(%q<coffee-script>, [">= 0"])
    s.add_dependency(%q<rails >= 3.1>, [">= 0"])
  end
end

