# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cowtech-js-rails"
  s.version = "1.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shogun"]
  s.date = "2012-04-16"
  s.description = "A set of Javascript libraries."
  s.email = "shogun_panda@me.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/cowtech_js.rb",
    "lib/cowtech_js/version.rb",
    "vendor/assets/javascripts/cowtech/accesskeys.js.coffee",
    "vendor/assets/javascripts/cowtech/autocomplete.js.coffee",
    "vendor/assets/javascripts/cowtech/bulk.js.coffee",
    "vendor/assets/javascripts/cowtech/calculator.js.coffee",
    "vendor/assets/javascripts/cowtech/clipboard.js.coffee",
    "vendor/assets/javascripts/cowtech/combobox.js.coffee",
    "vendor/assets/javascripts/cowtech/document.js.coffee",
    "vendor/assets/javascripts/cowtech/dynamic-table.js.coffee",
    "vendor/assets/javascripts/cowtech/form.js.coffee",
    "vendor/assets/javascripts/cowtech/google-analytics.js.coffee",
    "vendor/assets/javascripts/cowtech/keepalive.js.coffee",
    "vendor/assets/javascripts/cowtech/messages.js.coffee",
    "vendor/assets/javascripts/cowtech/modal.js.coffee",
    "vendor/assets/javascripts/cowtech/numeric.js.coffee",
    "vendor/assets/javascripts/cowtech/scroll.js.coffee",
    "vendor/assets/javascripts/cowtech/search.js.coffee",
    "vendor/assets/javascripts/cowtech/share.js.coffee",
    "vendor/assets/javascripts/cowtech/utils.js.coffee",
    "vendor/assets/javascripts/cowtech/wysiwyg.js.coffee"
  ]
  s.homepage = "http://github.com/ShogunPanda/cowtech-js-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = "1.8.15"
  s.summary = "A set of Javascript libraries."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<sprockets>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 3.1"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sprockets>, [">= 0"])
      s.add_dependency(%q<coffee-script>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.1"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sprockets>, [">= 0"])
    s.add_dependency(%q<coffee-script>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.1"])
  end
end

